package com.mqm.biz.model;
// Generated 2016-11-30 15:39:19 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * HStudent generated by hbm2java
 */
@Entity
@Table(name = "student")
public class HStudent implements java.io.Serializable {
	
	private static final long serialVersionUID = -3400752065636068463L;
	private String sno;
	private String sname;
	private String ssex;
	private Short sage;
	private String sdept;

	public HStudent() {
	}

	public HStudent(String sno, String sname) {
		this.sno = sno;
		this.sname = sname;
	}

	public HStudent(String sno, String sname, String ssex, Short sage, String sdept) {
		this.sno = sno;
		this.sname = sname;
		this.ssex = ssex;
		this.sage = sage;
		this.sdept = sdept;
	}

	@Id
	@GenericGenerator(name = "id_ass", strategy = "assigned")			
	@GeneratedValue(generator = "id_ass")
	@Column(name = "Sno", unique = true, nullable = false, length = 9)
	public String getSno() {
		return this.sno;
	}

	public void setSno(String sno) {
		this.sno = sno;
	}

	@Column(name = "Sname", nullable = false, length = 20)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Column(name = "Ssex", length = 4)
	public String getSsex() {
		return this.ssex;
	}

	public void setSsex(String ssex) {
		this.ssex = ssex;
	}

	@Column(name = "Sage")
	public Short getSage() {
		return this.sage;
	}

	public void setSage(Short sage) {
		this.sage = sage;
	}

	@Column(name = "Sdept", length = 20)
	public String getSdept() {
		return this.sdept;
	}

	public void setSdept(String sdept) {
		this.sdept = sdept;
	}

}
