package com.mqm.biz.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 2016-11-29 16:17:51 by Hibernate Tools 5.2.0.Beta1

/**
 * HUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user")
public class HUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5407917081620882715L;
	private String userId;
	private String organId;
	private String deptId;
	private String userName;
	private String realName;
	private String userPassword;
	private String userPosition;
	private String userTelephone;
	private String userMobile;
	private String userEmail;
	private boolean organAdmin;
	private boolean supervisor;
	private boolean userState;
	private Boolean deleteFlag;
	private String userMemo;
	private Date createTime;
	private String createUserid;
	private String createUsername;
	private Date lastModifyTime;
	private String lastModifyUserid;
	private String lastModifyUsername;

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "ORGAN_ID", length = 32)
	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	@Column(name = "DEPT_ID", length = 32)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "REAL_NAME", nullable = false, length = 100)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "USER_PASSWORD", nullable = false, length = 32)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "USER_POSITION", nullable = false, length = 100)
	public String getUserPosition() {
		return this.userPosition;
	}

	public void setUserPosition(String userPosition) {
		this.userPosition = userPosition;
	}

	@Column(name = "USER_TELEPHONE", length = 20)
	public String getUserTelephone() {
		return this.userTelephone;
	}

	public void setUserTelephone(String userTelephone) {
		this.userTelephone = userTelephone;
	}

	@Column(name = "USER_MOBILE", nullable = false, length = 20)
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "USER_EMAIL", nullable = false, length = 100)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "ORGAN_ADMIN", nullable = false, precision = 1, scale = 0)
	public boolean isOrganAdmin() {
		return this.organAdmin;
	}

	public void setOrganAdmin(boolean organAdmin) {
		this.organAdmin = organAdmin;
	}

	@Column(name = "SUPERVISOR", nullable = false, precision = 1, scale = 0)
	public boolean isSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(boolean supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "USER_STATE", nullable = false, precision = 1, scale = 0)
	public boolean isUserState() {
		return this.userState;
	}

	public void setUserState(boolean userState) {
		this.userState = userState;
	}

	@Column(name = "DELETE_FLAG", precision = 1, scale = 0)
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "USER_MEMO", length = 2000)
	public String getUserMemo() {
		return this.userMemo;
	}

	public void setUserMemo(String userMemo) {
		this.userMemo = userMemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "CREATE_USERID", nullable = false, length = 32)
	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	@Column(name = "CREATE_USERNAME", nullable = false, length = 100)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFY_TIME", length = 19)
	public Date getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	@Column(name = "LAST_MODIFY_USERID", length = 32)
	public String getLastModifyUserid() {
		return this.lastModifyUserid;
	}

	public void setLastModifyUserid(String lastModifyUserid) {
		this.lastModifyUserid = lastModifyUserid;
	}

	@Column(name = "LAST_MODIFY_USERNAME", length = 100)
	public String getLastModifyUsername() {
		return this.lastModifyUsername;
	}

	public void setLastModifyUsername(String lastModifyUsername) {
		this.lastModifyUsername = lastModifyUsername;
	}

}
